Repository nobl9/terraform-provider-nobl9, pull requests merged in 2024-09, with the labels that each got.

#297 chore: Update datadog site list
  docs/resources/agent.md
  docs/resources/direct_datadog.md
  nobl9/resource_agent.go
  nobl9/resource_direct.go
Labels: go, chore, patch

#299 chore: Update datadog site in examples and tests
  docs/resources/direct_datadog.md
  examples/resources/nobl9_direct_datadog/resource.tf
  nobl9/resource_agent_test.go
  nobl9/resource_direct_test.go
Labels: go, chore, patch

#300 chore: Goreleaser change deprecated flag
  .github/workflows/release.yml
  Makefile
Labels: chore, patch

#301 chore: Bump version number for release
  Makefile
  README.md
Labels: chore, patch

#302 chore: Update crazy-max/ghaction-import-gpg to v6
  .github/workflows/release.yml
Labels: chore, patch

#311 chore: Ignore nobl9-go in Renovate config
  .github/renovate.json5
Labels: chore, patch

#304 feat: PC-13723 Add SHR report support
  Makefile
  docs/index.md
  docs/resources/report_system_health_review.md
  examples/resources/nobl9_report_system_health_review/resource.tf
  go.mod
  go.sum
  nobl9/helpers.go
  nobl9/provider.go
  nobl9/resource_report.go
  nobl9/resource_report_test.go
  templates/index.md.tmpl
  templates/resources/report_system_health_review.md.tmpl
Labels: enhancement, passed-testing, go, minor

#312 test: PC-13893 Make acceptance test forward compatible
  nobl9/resource_slo_test.go
Labels: go

#313 chore: fix Splunk Observability acceptance test [PC-14221]
  nobl9/resource_agent_test.go
Labels: go, chore, patch

#314 chore: Bump version number for release
  README.md
Labels: chore, patch

#316 fix: enable alpha release channel
  go.mod
  go.sum
  nobl9/release_channel_schema.go
  nobl9/resource_agent_test.go
  nobl9/resource_direct_test.go
Labels: bug, go, patch
