Repository nobl9/terraform-provider-nobl9, pull requests merged in 2024-06, with the labels that each got.

#241 feat: PC-12978 Add composite examples
  docs/resources/slo.md
  examples/resources/nobl9_slo/resource.tf
Labels: enhancement, minor

#253 chore: Update acc-tests-dispatch.yml
  .github/workflows/acc-tests-dispatch.yml
Labels: chore, patch

#254 chore: Correct default project for acceptance tests dispatch workflow
  .github/workflows/acc-tests-dispatch.yml
Labels: chore, patch

#258 feat: Support for budget drop alerting condition
  docs/resources/alert_policy.md
  examples/resources/nobl9_alert_policy/resource.tf
  nobl9/resource_alert_policy.go
  nobl9/resource_alert_policy_test.go
Labels: enhancement, passed-testing, go, minor

#259 chore: Fix local provider installation guide
  dev-docs/DEVELOPMENT.md
Labels: chore, patch

#245 chore: PC-13335 Update URLs to main alerting docs
  docs/index.md
  docs/resources/agent.md
  docs/resources/alert_method_discord.md
  docs/resources/alert_method_email.md
  docs/resources/alert_method_jira.md
  docs/resources/alert_method_msteams.md
  docs/resources/alert_method_opsgenie.md
  docs/resources/alert_method_pagerduty.md
  docs/resources/alert_method_servicenow.md
  docs/resources/alert_method_slack.md
  docs/resources/alert_method_webhook.md
  docs/resources/direct_azure_monitor.md
  docs/resources/direct_honeycomb.md
  examples/resources/nobl9_direct_azure_monitor/resource.tf
  nobl9/resource_agent.go
  nobl9/resource_alertmethod.go
  nobl9/resource_direct.go
  templates/index.md.tmpl
  templates/resources/alert_method_discord.md.tmpl
  templates/resources/alert_method_email.md.tmpl
  templates/resources/alert_method_jira.md.tmpl
  templates/resources/alert_method_msteams.md.tmpl
  templates/resources/alert_method_opsgenie.md.tmpl
  templates/resources/alert_method_pagerduty.md.tmpl
  templates/resources/alert_method_servicenow.md.tmpl
  templates/resources/alert_method_slack.md.tmpl
  templates/resources/alert_method_webhook.md.tmpl
  templates/resources/direct_azure_monitor.md.tmpl
Labels: go, chore, patch
