Repository nobl9/terraform-provider-nobl9, pull requests merged in 2024-11, with the labels that each got.

#333 feat: Add new fields on DataSource setting that allow create Replay on SLO edit/creation - DataSource setting [PC-14402]
  Makefile
  README.md
  docs/index.md
  docs/resources/agent.md
  docs/resources/direct_appdynamics.md
  docs/resources/direct_azure_monitor.md
  docs/resources/direct_cloudwatch.md
  docs/resources/direct_datadog.md
  docs/resources/direct_dynatrace.md
  docs/resources/direct_gcm.md
  docs/resources/direct_honeycomb.md
  docs/resources/direct_lightstep.md
  docs/resources/direct_logic_monitor.md
  docs/resources/direct_newrelic.md
  docs/resources/direct_splunk.md
  docs/resources/slo.md
  examples/provider/provider.tf
  examples/resources/nobl9_direct_appdynamics/resource.tf
  examples/resources/nobl9_direct_azure_monitor/resource.tf
  examples/resources/nobl9_direct_cloudwatch/resource.tf
  examples/resources/nobl9_direct_datadog/resource.tf
  examples/resources/nobl9_direct_dynatrace/resource.tf
  examples/resources/nobl9_direct_honeycomb/resource.tf
  examples/resources/nobl9_direct_lightstep/resource.tf
  examples/resources/nobl9_direct_newrelic/resource.tf
  examples/resources/nobl9_direct_splunk/resource.tf
  nobl9/historical_data_retrieval_schema.go
  nobl9/resource_agent_test.go
  nobl9/resource_direct_test.go
  nobl9/resource_project_test.go
  nobl9/resource_slo.go
Labels: enhancement, passed-testing, go, minor

#303 test: Add test for LogicMonitor historical_data_retrieval
  nobl9/resource_direct_test.go
Labels: go

#345 fix: Set ForceNew to true for service in SLO
  nobl9/resource_slo.go
Labels: bug, go, patch

#346 fix: Revert "fix: Set ForceNew to true for service in SLO (#345)"
  nobl9/resource_slo.go
Labels: bug, go, patch

#342 feat: Trigger replay on SLO creation
  Makefile
  README.md
  docs/index.md
  docs/resources/slo.md
  examples/provider/provider.tf
  nobl9/resource_slo.go
Labels: enhancement, passed-testing, go, minor

#347 chore: Bump nobl9-go
  go.mod
  go.sum
Labels: go, chore, patch
