Repository nobl9/terraform-provider-nobl9, pull requests merged in 2024-08, with the labels that each got.

#279 chore: PC-13787 Distinguish composite 2.0 example
  docs/resources/slo.md
  examples/resources/nobl9_slo/resource.tf
  nobl9/resource_slo.go
  nobl9/resource_slo_composite.go
  templates/resources/slo.md.tmpl
Labels: go, chore, patch

#280 chore: PC-13797 Update ms teams alert method documentation.
  docs/resources/alert_method_msteams.md
  nobl9/resource_alertmethod.go
  templates/resources/alert_method_msteams.md.tmpl
Labels: go, chore, patch

#282 chore: PC-13787 Bump version
  Makefile
  README.md
  dev-docs/RELEASE.md
Labels: chore, patch

#291 chore: Skip GCM direct test
  nobl9/resource_direct_test.go
Labels: go, chore, patch

#285 chore: PC-13868 Fix composite 2.0 block uniqueness
  Makefile
  README.md
  docs/resources/slo.md
  nobl9/resource_slo.go
  nobl9/resource_slo_composite.go
Labels: passed-testing, go, chore, patch

#292 feat: add historical data retrieval support to Google Cloud Monitoring and Logic Monitor data sources
  docs/resources/direct_gcm.md
  docs/resources/direct_logic_monitor.md
  nobl9/resource_agent_test.go
  nobl9/resource_direct.go
  nobl9/resource_direct_test.go
Labels: enhancement, go, minor
