Repository nobl9/terraform-provider-nobl9, pull requests merged in 2024-02, with the labels that each got.

#154 chore: Add CI and checks [PC-11973]
  .github/pull_request_template.md
  .github/release-drafter.yml
  .github/renovate.json5
  .github/scripts/release-notes.sh
  .github/workflows/checks.yml
  .github/workflows/pr-title.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .github/workflows/vulns.yml
  .gitignore
  .golangci.yml
  DOCUMENTATION.md
  Makefile
  README.md
  bin/.keep
  codefresh.yml
  cspell.yaml
  docs/resources/alert_method_pagerduty.md
  docs/resources/direct_splunk_observability.md
  docs/resources/role_binding.md
  docs/resources/slo.md
  examples/resources/nobl9_alert_method_pagerduty/resource.tf
  examples/resources/nobl9_direct_splunk_observability/resource.tf
  examples/resources/nobl9_role_binding/resource.tf
  examples/resources/nobl9_slo/resource.tf
  main.go
  nobl9/data_source.go
  nobl9/historical_data_retrieval_schema.go
  nobl9/provider.go
  nobl9/resource_agent_test.go
  nobl9/resource_alertmethod.go
  nobl9/resource_alertmethod_test.go
  nobl9/resource_direct.go
  nobl9/resource_role_binding_test.go
  nobl9/resource_service_test.go
  nobl9/resource_slo_test.go
  package.json
  renovate.json
  scripts/check-formatting.sh
  scripts/check-generate.sh
  scripts/check-trailing-whitespaces.js
  scripts/ensure_installed.sh
  scripts/format-cspell-config.js
  scripts/makefile-help.awk
Labels: chore, patch

#158 chore: Update pr-title.yml
  .github/workflows/pr-title.yml
Labels: chore, patch

#143 feat: Azure Monitor Logs SLOs support [PC-11534]
  Makefile
  README.md
  cspell.yaml
  docs/index.md
  docs/resources/slo.md
  examples/provider/provider.tf
  nobl9/resource_slo.go
  nobl9/resource_slo_test.go
Labels: enhancement, passed-testing, go, minor

#165 chore: adjust version to 0.23.0
  .github/scripts/release-notes.sh
  Makefile
  README.md
  docs/index.md
  examples/provider/provider.tf
Labels: chore, patch

#166 chore: Rewrite Codefresh pipeline to GH workflow for acceptance tests
  .github/workflows/acc-tests.yml
  .github/workflows/release.yml
  .github/workflows/unit-tests.yml
  Makefile
  codefresh.yml
  nobl9/data_source_test.go
  nobl9/provider.go
  nobl9/provider_test.go
  nobl9/resource_agent_test.go
  nobl9/resource_alert_policy_test.go
  nobl9/resource_alertmethod_test.go
  nobl9/resource_direct_test.go
  nobl9/resource_project_test.go
  nobl9/resource_role_binding_test.go
  nobl9/resource_service_test.go
  nobl9/resource_slo_test.go
Labels: go, chore, patch

#167 chore: Add release candidate workflow
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: chore, patch

#168 chore: Fix release workflow
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: chore, patch

#169 chore: Fix acceptance tests
  .github/workflows/acc-tests.yml
Labels: chore, patch

#170 chore: Fix acceptance tests env variable names
  .github/workflows/acc-tests.yml
Labels: go, chore, patch

#172 chore: Adjust acceptance tests workflow
  .github/workflows/acc-tests.yml
Labels: chore, patch
