Repository nobl9/terraform-provider-nobl9, pull requests merged in 2024-07, with the labels that each got.

#266 fix: PC-13500 dynamic date in BudgetAdjustment acceptance tests
  nobl9/resource_budgetadjustment_test.go
Labels: bug, go, patch

#270 chore: PC-13627 Add "depends_on" suggestion to docs for composites v2
  docs/resources/slo.md
  examples/resources/nobl9_slo/resource.tf
  templates/resources/slo.md.tmpl
Labels: chore, patch

#263 chore: PC-13444 Extract helper funcs
  nobl9/helpers.go
  nobl9/metadata_schema.go
  nobl9/provider.go
  nobl9/resource_budgetadjustment.go
  nobl9/resource_slo.go
  nobl9/resource_slo_composite.go
  nobl9/validate.go
Labels: go, chore, patch

#265 feat: PC-13482 Add static validation from SDK
  .github/CODEOWNERS
  Makefile
  README.md
  nobl9/helpers.go
  nobl9/historical_data_retrieval_schema.go
  nobl9/log_collection_schema.go
  nobl9/metadata_schema.go
  nobl9/query_delay_schema.go
  nobl9/release_channel_schema.go
  nobl9/resource_agent.go
  nobl9/resource_alert_policy.go
  nobl9/resource_alertmethod.go
  nobl9/resource_budgetadjustment_test.go
  nobl9/resource_direct.go
  nobl9/resource_project.go
  nobl9/resource_role_binding.go
  nobl9/resource_role_binding_test.go
  nobl9/resource_service.go
Labels: enhancement, passed-testing, go, minor

#267 chore: PC-13571 Add testType field to ThousandEyes
  docs/resources/slo.md
  nobl9/resource_slo.go
  nobl9/resource_slo_test.go
Labels: go, chore, patch

#275 chore: gitsync updates
  .github/release-drafter.yml
  .github/renovate.json5
  .github/scripts/release-notes.sh
  .golangci.yml
Labels: chore, patch
