Repository nobl9/terraform-provider-nobl9, pull requests merged in 2024-03, with the labels that each got.

#179 chore: PC-12144 Make Honeycomb integration generally available
  docs/resources/direct_honeycomb.md
  nobl9/resource_agent.go
  nobl9/resource_direct.go
  nobl9/resource_slo.go
  templates/resources/direct_honeycomb.md.tmpl
Labels: go, chore, patch

#182 chore: Fix the goreleaser workflow
  .github/workflows/acc-tests.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
Labels: chore, patch

#186 chore: Introduce SOC-2 compliant release workflow
  .github/workflows/release.yml
  dev-docs/DEVELOPMENT.md
  dev-docs/RELEASE.md
Labels: chore, patch

#181 feat: add Lightstep URL [PC-12053]
  docs/resources/agent.md
  docs/resources/direct_lightstep.md
  go.mod
  go.sum
  nobl9/resource_agent.go
  nobl9/resource_agent_test.go
  nobl9/resource_direct.go
  nobl9/resource_direct_test.go
Labels: enhancement, passed-testing, go, minor, release-notes

#177 PC-11995 + PC-10979 feat: AlertPolicy - add support for `alerting_window` and `cooldown` parameters
  Makefile
  docs/resources/alert_policy.md
  examples/resources/nobl9_alert_policy/resource.tf
  nobl9/resource_alert_policy.go
  nobl9/resource_alert_policy_test.go
  nobl9/resource_slo_test.go
  templates/resources/alert_policy.md.tmpl
Labels: passed-testing, go, release-notes

#189 test: fix lightstep direct test
  dev-docs/DEVELOPMENT.md
  nobl9/resource_agent_test.go
  nobl9/resource_direct_test.go
Labels: go

#190 fix: Default values for alert policy empty `cooldown` and `lasts_for` to be backward compatible
  .github/workflows/acc-tests-dispatch.yml
  dev-docs/DEVELOPMENT.md
  nobl9/resource_alert_policy.go
Labels: bug, go, patch

#193 chore: Add logo and improve README
  README.md
  dev-docs/DEVELOPMENT.md
Labels: chore, patch

#195 chore: Update README.md logo
  README.md
Labels: chore, patch

#197 chore: Fix README.md logo
  README.md
Labels: chore, patch

#198 chore: Update Release Drafter
  .github/pull_request_template.md
  .github/release-drafter.yml
  .github/scripts/release-notes.sh
  .markdownlint.yaml
  Makefile
  README.md
  dev-docs/DEVELOPMENT.md
Labels: chore, patch

#200 chore: Update keys in release.yml
  .github/workflows/release.yml
Labels: chore, patch
