Repository nobl9/terraform-provider-nobl9, pull requests merged in 2024-05, with the labels that each got.

#216 PC-12653+PC-12085 feat: Allow to set mathematical operator for burnedBudget alerting condition
  docs/resources/alert_policy.md
  examples/resources/nobl9_alert_policy/resource.tf
  nobl9/resource_alert_policy.go
  nobl9/resource_alert_policy_test.go
  nobl9/resource_slo_test.go
Labels: passed-testing, go

#225 chore: Update pr-title.yml
  .github/workflows/pr-title.yml
Labels: chore, patch

#175 feat: PC-11815 add budget adjustments terraform support
  cspell.yaml
  docs/resources/budget_adjustment.md
  examples/resources/nobl9_budget_adjustment/resource.tf
  go.mod
  nobl9/provider.go
  nobl9/resource_budgetadjustment.go
  nobl9/resource_budgetadjustment_test.go
  nobl9/validate.go
  nobl9/validate_test.go
  templates/resources/budget_adjustment.md.tmpl
Labels: enhancement, go, minor

#229 fix: PC-11815 terraform tests fix
  nobl9/resource_budgetadjustment_test.go
Labels: bug, go, patch
