Repository nobl9/terraform-provider-nobl9, pull requests merged in 2024-12, with the labels that each got.

#352 chore: Remove deprecated 'Subject' and 'Body' support from Email alert method.
  docs/resources/alert_method_email.md
  nobl9/resource_alertmethod.go
  nobl9/resource_alertmethod_test.go
Labels: passed-testing, go, chore, breaking-change, patch

#295 feat: PC-13893 Deprecate usage of objective's value field for Composite SLOs
  Makefile
  docs/resources/slo.md
  examples/resources/nobl9_slo/resource.tf
  go.mod
  go.sum
  nobl9/resource_slo.go
  nobl9/resource_slo_test.go
Labels: enhancement, go, minor

#355 chore: Bump go version to 1.23.4
  go.mod
Labels: go, chore, patch

#357 fix: Fix failing acceptance tests
  go.mod
  go.sum
  nobl9/resource_slo_test.go
Labels: bug, go, patch

#358 chore: PC-15033 Remove experimental fields
  .golangci.yml
  docs/resources/agent.md
  docs/resources/direct_appdynamics.md
  docs/resources/direct_azure_monitor.md
  docs/resources/direct_cloudwatch.md
  docs/resources/direct_datadog.md
  docs/resources/direct_dynatrace.md
  docs/resources/direct_gcm.md
  docs/resources/direct_honeycomb.md
  docs/resources/direct_lightstep.md
  docs/resources/direct_logic_monitor.md
  docs/resources/direct_newrelic.md
  docs/resources/direct_splunk.md
  examples/resources/nobl9_direct_appdynamics/resource.tf
  examples/resources/nobl9_direct_azure_monitor/resource.tf
  examples/resources/nobl9_direct_cloudwatch/resource.tf
  examples/resources/nobl9_direct_datadog/resource.tf
  examples/resources/nobl9_direct_dynatrace/resource.tf
  examples/resources/nobl9_direct_honeycomb/resource.tf
  examples/resources/nobl9_direct_lightstep/resource.tf
  examples/resources/nobl9_direct_logic_monitor/resource.tf
  examples/resources/nobl9_direct_newrelic/resource.tf
  examples/resources/nobl9_direct_splunk/resource.tf
  go.mod
  nobl9/anomaly_config_schema_test.go
  nobl9/historical_data_retrieval_schema.go
  nobl9/resource_agent_test.go
  nobl9/resource_direct_test.go
  nobl9/resource_report_test.go
Labels: passed-testing, go, chore, patch

#361 chore: Bump version number for release
  Makefile
  README.md
  docs/index.md
  examples/provider/provider.tf
Labels: chore, patch

#351 feat: Switch Service resource to Terraform Plugin Framework [PC-14988]
  .golangci.yml
  cspell.yaml
  docs/index.md
  docs/resources/service.md
  go.mod
  go.sum
  internal/frameworkprovider/env_configurable_string.go
  internal/frameworkprovider/helpers.go
  internal/frameworkprovider/helpers_test.go
  internal/frameworkprovider/metadata_labels_block.go
  internal/frameworkprovider/metadata_schema.go
  internal/frameworkprovider/plan_check_test.go
  internal/frameworkprovider/provider.go
  internal/frameworkprovider/provider_model.go
  internal/frameworkprovider/provider_test.go
  internal/frameworkprovider/sdk_client.go
  internal/frameworkprovider/service_resource.go
  internal/frameworkprovider/service_resource_model.go
  internal/frameworkprovider/service_resource_test.go
  internal/frameworkprovider/templates_test.go
  internal/frameworkprovider/test_data/templates/service_resource.hcl.tmpl
  main.go
  nobl9/provider.go
  nobl9/resource_service.go
  nobl9/resource_service_test.go
  nobl9/resource_slo_test.go
Labels: enhancement, passed-testing, go, minor

#365 chore: Update version to 0.35.0
  Makefile
  README.md
  docs/index.md
  examples/provider/provider.tf
Labels: chore, patch

#366 fix: Correct version handling for Terraform Plugin Framework and fix acceptance tests
  Makefile
  internal/frameworkprovider/doc.go
  internal/frameworkprovider/provider_test.go
  internal/frameworkprovider/service_resource_test.go
  main.go
  nobl9/data_source_test.go
  nobl9/doc.go
  nobl9/provider.go
  nobl9/provider_test.go
  nobl9/resource_agent_test.go
  nobl9/resource_alert_policy_test.go
  nobl9/resource_alertmethod_mock.go
  nobl9/resource_alertmethod_test.go
  nobl9/resource_budgetadjustment_test.go
  nobl9/resource_direct_test.go
  nobl9/resource_project_test.go
  nobl9/resource_report_test.go
  nobl9/resource_role_binding_test.go
  nobl9/resource_slo_test.go
Labels: bug, go, patch

#369 chore: Update Makefile to compile Provider binary on any platform
  Makefile
  cspell.yaml
Labels: chore, patch

#370 fix: Correct version handling
  Makefile
Labels: bug, patch
