Repository nobl9/terraform-provider-nobl9, pull requests merged in 2025-04, with the labels that each got.

#425 feat: Move Project resource to Provider framework
  docs/resources/project.md
  docs/resources/service.md
  docs/resources/slo.md
  go.mod
  go.sum
  internal/frameworkprovider/metadata_labels_block.go
  internal/frameworkprovider/project_resource.go
  internal/frameworkprovider/project_resource_model.go
  internal/frameworkprovider/project_resource_test.go
  internal/frameworkprovider/provider.go
  internal/frameworkprovider/provider_test.go
  internal/frameworkprovider/sdk_client.go
  internal/frameworkprovider/service_resource.go
  internal/frameworkprovider/service_resource_test.go
  internal/frameworkprovider/test_data/templates/project_resource.hcl.tmpl
  nobl9/provider.go
  nobl9/resource_project.go
  nobl9/resource_project_test.go
  nobl9/resource_report.go
  nobl9/resource_slo.go
Labels: enhancement, go, breaking-change, minor

#417 fix: Correct checks for fetching Nobl9 objects
  nobl9/helpers.go
  nobl9/resource_agent.go
  nobl9/resource_alert_policy.go
  nobl9/resource_alertmethod.go
  nobl9/resource_budgetadjustment.go
  nobl9/resource_direct.go
  nobl9/resource_report.go
  nobl9/resource_slo.go
Labels: bug, go, patch

#428 feat: SLO NO DATA alerts - customizable alertsAfter
  Makefile
  docs/resources/slo.md
  examples/resources/nobl9_slo/resource.tf
  go.mod
  go.sum
  nobl9/anomaly_config_schema.go
  nobl9/anomaly_config_schema_test.go
Labels: enhancement, passed-testing, go, minor
