Repository nobl9/terraform-provider-nobl9, pull requests merged in 2025-05, with the labels that each got.

#444 chore: switch to JSON cspell config
  cspell.json
  cspell.yaml
  package.json
  scripts/format-cspell-config.js
Labels: javascript, chore, patch

#441 feat: Allow to configure email alert method to send plain text
  Makefile
  README.md
  docs/index.md
  docs/resources/alert_method_discord.md
  docs/resources/alert_method_email.md
  docs/resources/alert_method_jira.md
  docs/resources/alert_method_msteams.md
  docs/resources/alert_method_opsgenie.md
  docs/resources/alert_method_pagerduty.md
  docs/resources/alert_method_servicenow.md
  docs/resources/direct_appdynamics.md
  docs/resources/direct_azure_monitor.md
  docs/resources/direct_dynatrace.md
  docs/resources/direct_honeycomb.md
  docs/resources/direct_influxdb.md
  docs/resources/direct_instana.md
  docs/resources/direct_logic_monitor.md
  docs/resources/direct_newrelic.md
  docs/resources/direct_splunk.md
  docs/resources/direct_sumologic.md
  docs/resources/report_system_health_review.md
  docs/resources/slo.md
  examples/provider/provider.tf
  examples/resources/nobl9_alert_method_discord/resource.tf
  examples/resources/nobl9_alert_method_email/resource.tf
  examples/resources/nobl9_alert_method_jira/resource.tf
  examples/resources/nobl9_alert_method_msteams/resource.tf
  examples/resources/nobl9_alert_method_opsgenie/resource.tf
  examples/resources/nobl9_alert_method_pagerduty/resource.tf
  examples/resources/nobl9_alert_method_servicenow/resource.tf
  examples/resources/nobl9_direct_appdynamics/resource.tf
  examples/resources/nobl9_direct_azure_monitor/resource.tf
  examples/resources/nobl9_direct_dynatrace/resource.tf
  examples/resources/nobl9_direct_honeycomb/resource.tf
  examples/resources/nobl9_direct_influxdb/resource.tf
  examples/resources/nobl9_direct_instana/resource.tf
  examples/resources/nobl9_direct_logic_monitor/resource.tf
  examples/resources/nobl9_direct_newrelic/resource.tf
  examples/resources/nobl9_direct_splunk/resource.tf
  examples/resources/nobl9_direct_sumologic/resource.tf
  examples/resources/nobl9_report_system_health_review/resource.tf
  examples/resources/nobl9_slo/resource.tf
  go.mod
  go.sum
  nobl9/resource_alertmethod.go
  nobl9/resource_alertmethod_test.go
Labels: enhancement, passed-testing, go, minor

#443 feat: Add send resolution to Service Now
  docs/resources/alert_method_servicenow.md
  nobl9/resource_alertmethod.go
  nobl9/resource_alertmethod_test.go
Labels: enhancement, passed-testing, go, minor

#449 fix: Fix acceptance tests of Email AlertMethod
  nobl9/resource_alertmethod_test.go
Labels: bug, go, patch

#450 fix: Correct objective name warning
  nobl9/resource_slo.go
Labels: bug, go, patch

#451 chore: Bump version to 0.40.1
  Makefile
  README.md
  docs/index.md
  examples/provider/provider.tf
Labels: chore, patch
