Repository nobl9/terraform-provider-nobl9, pull requests merged in 2025-01, with the labels that each got.

#377 fix: Perform replay only if SLO is created successfully
  nobl9/resource_slo.go
Labels: bug, passed-testing, go, patch

#379 chore: Update adjustments description
  docs/resources/budget_adjustment.md
  templates/resources/budget_adjustment.md.tmpl
Labels: chore, patch

#380 chore: Update value description
  docs/resources/slo.md
  nobl9/resource_slo.go
Labels: go, chore, patch

#383 feat: Add custom headers support for Webhook AlertMethod
  docs/resources/alert_method_webhook.md
  go.mod
  go.sum
  nobl9/resource_alertmethod.go
  nobl9/resource_alertmethod_test.go
Labels: enhancement, go, minor

#384 chore: Update broken link for webhook
  docs/resources/alert_method_webhook.md
  templates/resources/alert_method_webhook.md.tmpl
Labels: chore, patch

#388 fix: PC-9592 Update opsgenie, slack URLs in tests
  docs/resources/alert_method_slack.md
  examples/resources/nobl9_alert_method_slack/resource.tf
  nobl9/resource_alert_policy_test.go
  nobl9/resource_alertmethod_test.go
Labels: bug, go, patch

#375 feat: Support for single query splunk ratio SLOs [PC-13052]
  docs/resources/slo.md
  nobl9/resource_slo.go
  nobl9/resource_slo_test.go
Labels: enhancement, passed-testing, go, minor

#390 chore: Fix failing test because of wrong formatting multiline string [PC-13052]
  nobl9/resource_slo_test.go
Labels: go, chore, patch

#359 feat: Add website metrics to LogicMonitor [PC-15088]
  docs/resources/slo.md
  go.mod
  go.sum
  nobl9/resource_slo.go
  nobl9/resource_slo_test.go
Labels: enhancement, passed-testing, go, minor

#371 feat: Support promql field in GCM terraform [PC-14302]
  docs/resources/slo.md
  nobl9/resource_slo.go
  nobl9/resource_slo_test.go
Labels: enhancement, passed-testing, go, minor

#392 chore: fix message error in test that validates metrics.
  nobl9/resource_slo_test.go
Labels: go, chore, patch

#394 chore: Update version to 0.37.0
  Makefile
  README.md
  docs/index.md
  examples/provider/provider.tf
Labels: chore, patch
